# Generated by Django 6.0.1 on 2026-01-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("send_notes", models.BooleanField(default=True, verbose_name="メモを送信")),
                ("send_digests", models.BooleanField(default=True, verbose_name="ダイジェストを送信")),
                ("send_docs", models.BooleanField(default=False, verbose_name="文書を送信")),
                ("send_raw_logs", models.BooleanField(default=False, verbose_name="生ログを送信")),
                ("pii_masking", models.BooleanField(default=True, verbose_name="PII マスキング")),
                ("llm_enabled", models.BooleanField(default=True, verbose_name="LLM 有効")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー設定",
                "verbose_name_plural": "ユーザー設定",
            },
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255, verbose_name="キー")),
                ("value", models.TextField(verbose_name="値")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("writing", "文章スタイル"),
                            ("lifestyle", "生活習慣"),
                            ("work", "仕事"),
                            ("health", "健康"),
                            ("decision", "意思決定"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "好み・ルール",
                "verbose_name_plural": "好み・ルール",
                "ordering": ["category", "key"],
                "unique_together": {("user", "key")},
            },
        ),
    ]
