# Generated by Django 6.0.1 on 2026-01-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("llm_call", "LLM呼び出し"),
                            ("data_export", "データエクスポート"),
                            ("data_delete", "データ削除"),
                            ("login", "ログイン"),
                            ("logout", "ログアウト"),
                        ],
                        max_length=50,
                        verbose_name="イベント種類",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="ペイロード")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "監査ログ",
                "verbose_name_plural": "監査ログ",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "event_type"], name="audits_audi_user_id_d11f41_idx"),
                    models.Index(fields=["created_at"], name="audits_audi_created_61fc5f_idx"),
                ],
            },
        ),
    ]
