# Generated by Django 6.0.1 on 2026-01-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("body", models.TextField(blank=True, verbose_name="本文")),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="タグ")),
                (
                    "importance",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "普通"), (3, "高"), (4, "重要"), (5, "最重要")],
                        default=2,
                        verbose_name="重要度",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "自分のみ"), ("shared", "共有")],
                        default="private",
                        max_length=20,
                        verbose_name="公開範囲",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "メモ",
                "verbose_name_plural": "メモ",
                "ordering": ["-updated_at"],
            },
        ),
    ]
