# Generated by Django 6.0.1 on 2026-01-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("file", models.FileField(upload_to="documents/files/", verbose_name="ファイル")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("txt", "テキスト"), ("md", "Markdown")],
                        max_length=10,
                        verbose_name="ファイル形式",
                    ),
                ),
                ("extracted_text", models.TextField(blank=True, verbose_name="抽出テキスト")),
                ("summary", models.TextField(blank=True, verbose_name="要約")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "処理待ち"),
                            ("processing", "処理中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="エラーメッセージ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "文書",
                "verbose_name_plural": "文書",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_index", models.IntegerField(verbose_name="チャンク番号")),
                ("content", models.TextField(verbose_name="内容")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="メタデータ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="documents.document"
                    ),
                ),
            ],
            options={
                "verbose_name": "文書チャンク",
                "verbose_name_plural": "文書チャンク",
                "ordering": ["document", "chunk_index"],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
