# Generated by Django 6.0.1 on 2026-01-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("due_at", models.DateTimeField(blank=True, null=True, verbose_name="期限")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "普通"), (3, "高"), (4, "緊急")], default=2, verbose_name="優先度"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("todo", "未着手"), ("doing", "進行中"), ("done", "完了")],
                        default="todo",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="タグ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "タスク",
                "verbose_name_plural": "タスク",
                "ordering": ["-priority", "due_at", "-created_at"],
            },
        ),
    ]
