# Generated by Django 6.0.1 on 2026-01-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="日付")),
                ("raw_text", models.TextField(verbose_name="内容")),
                (
                    "mood",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "😢 とても悪い"),
                            (2, "😕 悪い"),
                            (3, "😐 普通"),
                            (4, "🙂 良い"),
                            (5, "😊 とても良い"),
                        ],
                        null=True,
                        verbose_name="気分",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="logs/attachments/", verbose_name="添付"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "日常ログ",
                "verbose_name_plural": "日常ログ",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="DailyDigest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.TextField(verbose_name="要約")),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="タグ")),
                ("topics", models.JSONField(blank=True, default=list, verbose_name="トピック")),
                ("actions", models.JSONField(blank=True, default=list, verbose_name="アクション")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="digest", to="logs.dailylog"
                    ),
                ),
            ],
            options={
                "verbose_name": "日常ダイジェスト",
                "verbose_name_plural": "日常ダイジェスト",
                "ordering": ["-created_at"],
            },
        ),
    ]
