# Generated by Django 6.0.1 on 2026-01-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="新しい会話", max_length=255, verbose_name="タイトル")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットセッション",
                "verbose_name_plural": "チャットセッション",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "ユーザー"), ("assistant", "アシスタント"), ("system", "システム")],
                        max_length=20,
                        verbose_name="役割",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("citations", models.JSONField(blank=True, default=list, verbose_name="引用")),
                ("next_questions", models.JSONField(blank=True, default=list, verbose_name="追加質問")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="assistant.chatsession"
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットメッセージ",
                "verbose_name_plural": "チャットメッセージ",
                "ordering": ["created_at"],
            },
        ),
    ]
