# Generated by Django 6.0.1 on 2026-01-09 23:41

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("note", "メモ"),
                            ("digest", "ダイジェスト"),
                            ("chunk", "文書チャンク"),
                            ("task", "タスク"),
                            ("preference", "好み"),
                        ],
                        max_length=20,
                        verbose_name="コンテンツ種類",
                    ),
                ),
                ("content_id", models.IntegerField(verbose_name="コンテンツID")),
                ("content_text", models.TextField(verbose_name="コンテンツテキスト")),
                ("content_title", models.CharField(blank=True, max_length=255, verbose_name="タイトル")),
                ("vector", pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "埋め込み",
                "verbose_name_plural": "埋め込み",
                "indexes": [models.Index(fields=["user", "content_type"], name="retrieval_e_user_id_838a72_idx")],
                "unique_together": {("content_type", "content_id")},
            },
        ),
    ]
